console.log("===================== DOM MANIPULATION =====================");
console.log(document);

console.log("");
console.log("============= Selectors =============");
// *1) document.getElementById( id ) - Selects ONE element by the given id
//  2) document.getElementsByClassName( class ) - Selects COLLECTION of elements by the given class ( even if there is one element, it is still in a collection )
//  3) document.getElementsByTagName( tag ) - Selects COLLECTION of elements by the given HTML tag ( even if there is one element, it is still in a collection )
// *4) document.querySelector( css selector ) - Selects the FIRST entity of any query selector result
// *5) document.querySelectorAll( css selector ) - Selects COLLECTION of entities of any query selector result

const whatever = document.querySelector("h1");
const firstParagraph = document.querySelector("[customName='Paragraph One']") // select by attribute
const secondParagraph = document.getElementsByTagName("p")[1];
const firstDiv = document.getElementById("first-div");
const secondDiv = document.querySelector(".second-div");
const thirdDiv = secondDiv.nextElementSibling;


console.log("");
console.log("============= Get or Change data of an Element =============");

// ***** TEXT *****
console.log(whatever.innerText); // shows the human-readable text, excludes content hidden by css
console.log(whatever.textContent); // includes content hidden by css

// ***** ATTRIBUTES *****
whatever.firstChild.removeAttribute("hidden");
const customAttributeValue = firstParagraph.getAttribute("customAttribute");
console.log(customAttributeValue);
firstParagraph.setAttribute("bob", "bobsky"); // add new attribute (bob) and value (bobsky)

// ***** STYLE *****
// element.style.nameOfCssProperty = ""
whatever.style.color = "darkred";


console.log("");
console.log("============= Creating and Appending new Elements =============");

// ====== Using document.createElement("element-name") ======
const h2 = document.createElement("h2");
h2.innerText = "h2 generated by JS";
firstDiv.appendChild(h2);

const paragraph = document.createElement("p");
paragraph.innerText = "This is paragraph created with document.createElement('p')";
paragraph.style.backgroundColor = "green";
firstDiv.append(paragraph);

console.log(firstDiv.children);


// ====== Using innerHTML ======

secondDiv.innerHTML = `<h2>This is created using innerHTML</h2>`
secondDiv.innerHTML += "<p style='color:magenta;'>Hello this is a magenta paragraph</p>";

// document.getElementById("magenta-text").style.color = "gold";

const fullName = "Bob Bobsky";
secondDiv.innerHTML = "";
secondDiv.innerHTML = `
    <h2>This is created using innerHtml</h2>
    <p id="magenta-text" style='color:magenta;'>Hello this is a magenta paragraph</p>
    <h3>Hello from <i>${fullName}</i></h3>
    <p>Yes, you can use string interpolation when manipulating with elements :)</p>
`;

// NOTE: We can select dynamically added elements as well 
document.getElementById("magenta-text").style.color = "gold";


// BAD APPROACH
// Here the browser will auto-generate a closing tag (</ul>). The whole list structure will be broken.

// thirdDiv.innerHTML = "<ul>"; // </ul> added automatically
// for (let i = 0; i < 10; i++) {
//     thirdDiv.innerHTML += `<li>Item ${i + 1}</li>`
// }
// thirdDiv.innerHTML += "</ul>";

// GOOD APPROACH
// Instead you can build a string containing the needed html, and then just assign it to the element's innerHTML
let thirdDivHtml = "<ul>"
for (let i = 0; i < 10; i++) {
    thirdDivHtml += `<li>Item ${i + 1}</li>`
}
thirdDivHtml += "</ul>"

thirdDiv.innerHTML = thirdDivHtml;