console.log("===================== DOM MANIPULATION =====================");
console.log(document);

console.log("");
console.log("============= Selectors =============");
// *1) document.getElementById( id ) - Selects ONE element by the given id
//  2) document.getElementsByClassName( class ) - Selects COLLECTION of elements by the given class ( even if there is one element, it is still in a collection )
//  3) document.getElementsByTagName( tag ) - Selects COLLECTION of elements by the given HTML tag ( even if there is one element, it is still in a collection )
// *4) document.querySelector( css selector ) - Selects the FIRST entity of any query selector result
// *5) document.querySelectorAll( css selector ) - Selects COLLECTION of entities of any query selector result

const whatever = document.querySelector("h1");
const firstParagraph = document.querySelector("[customName='Paragraph One']")
const secondParagraph = document.getElementsByTagName("p")[1];
const firstDiv = document.getElementById("first-div");
const secondDiv = document.querySelector(".second-div");
const thirdDiv = secondDiv.nextElementSibling;


console.log("");
console.log("============= Get or Change data of an Element =============");

// ***** TEXT *****
console.log(whatever.innerText); // shows the human-readable text, excludes content hidden by css
console.log(whatever.textContent); // includes content hidden by css

// ***** ATTRIBUTES *****
whatever.firstChild.removeAttribute("hidden");
const customAttributeValue = firstParagraph.getAttribute("customAttribute");
console.log(customAttributeValue);
firstParagraph.setAttribute("bob", "bobsky");

// ***** STYLE *****
whatever.style.color = "darkred";


console.log("");
console.log("============= Creating and Appending new Elements =============");

// ====== Using document.createElement("element-name") ======
const h2 = document.createElement("h2");
h2.innerText = "h2 generated by JS";
firstDiv.appendChild(h2);









